"use client";
import { FormEvent, useState } from "react";

const starterPrompt = `Build a professional website for my business that looks like it was custom-designed by a top agency rather than generated from a template. Before building it, understand my business, customers, competitors and industry. Determine the primary action I want visitors to take. Create the positioning, copy, visual direction, navigation and mobile experience around that goal. My business is: [BUSINESS / WEBSITE / DESCRIPTION].`;
const kit = ["Website Starter Prompt","Leading AI Website Options","Website Launch Checklist","Domain Guide","DIY Website Path","FreeSites Build Opportunity"];
function Arrow(){return <span aria-hidden="true">↗</span>}

export default function SitesV3Home(){
 const [email,setEmail]=useState(""); const [submitted,setSubmitted]=useState(false); const [copied,setCopied]=useState(false);
 function submit(e:FormEvent){e.preventDefault();if(email.trim())setSubmitted(true)}
 async function copyPrompt(){await navigator.clipboard.writeText(starterPrompt);setCopied(true);setTimeout(()=>setCopied(false),1800)}
 return <main>
  <header className="nav shell"><a className="wordmark" href="#top" aria-label="FreeSites home"><span>Free</span>Sites</a><nav aria-label="Main navigation"><a href="#shift">What changed</a><a href="#paths">Two free paths</a><a className="nav-cta" href="#start">Start free <Arrow/></a></nav></header>
  <section className="hero shell" id="top"><div className="eyebrow"><span className="pulse"/> THE WEBSITE ECONOMY HAS CHANGED.</div><div className="hero-grid"><div className="hero-copy"><h1><span>WEBSITES USED TO</span><span>COST <em>$5,000+.</em></span><span className="blue">NOW YOU CAN BUILD</span><span className="blue">ONE FREE.</span><span>OR HAVE FREESITES</span><span>BUILD IT FREE.</span></h1><p>AI has changed website building forever.<br/><b>FreeSites helps you take advantage of it.</b></p></div><div className="unlock" id="start"><p className="overline">Unlock the Free Website Starter Kit</p><h2>Your website. <span>Unlocked.</span></h2><p className="bundle-line"><b>FREE Prompt</b> • Leading AI Options • Domain Guide • Launch Checklist • <b>FREE Build Opportunity</b></p>{submitted?<div className="success" role="status"><b>You’re in.</b><br/>Your free start is ready.<small>Email delivery will be connected next.</small></div>:<form onSubmit={submit}><label htmlFor="email">One email unlocks everything</label><div className="email-row"><input id="email" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@business.com"/><button type="submit">START FREE <Arrow/></button></div><small>No credit card. No obligation.</small></form>}</div></div></section>
  <section className="marquee" aria-label="Free resources"><div>FREE PROMPT <i>✦</i> FREE DOMAIN GUIDE <i>✦</i> FREE LAUNCH CHECKLIST <i>✦</i> FREE WEBSITE PATH <i>✦</i> FREE BUILD OPPORTUNITY <i>✦</i> FREE PROMPT <i>✦</i> FREE DOMAIN GUIDE</div></section>
  <section className="shift shell" id="shift"><div><p className="section-num">01 / THE SHIFT</p><h2>The expensive part<br/>was the <i>making.</i><br/>That just changed.</h2></div><div className="shift-copy"><p className="lead"><strong>40%+ of the web still runs on WordPress.</strong> It helped define the previous website era and remains enormously important.</p><p>Businesses often paid <strong>$5,000+</strong> for websites assembled using WordPress, themes, plugins, page builders, designers and developers. AI is changing the economics of that production—not erasing what came before.</p><p className="shift-conclusion">The old way isn&apos;t suddenly bad. It&apos;s suddenly not the only way.</p><p>AI is rapidly changing those economics. The question is no longer simply, “Can I afford a professional website?”</p><blockquote>“Which tools should I use—and how do I turn what they create into a website that actually works?”</blockquote><p>That’s where FreeSites comes in. We continually test the newest website-building technology, so you don’t have to.</p></div></section>
  <section className="paths" id="paths"><div className="shell"><p className="section-num light">02 / TWO WAYS TO START</p><h2>Choose your kind<br/>of <i>free.</i></h2><div className="path-grid"><article className="path-card diy"><div className="card-top"><span>PATH 01</span><span>FOR THE CURIOUS</span></div><div className="path-icon">⌁</div><h3>BUILD IT<br/>YOURSELF — <i>FREE</i></h3><p>Meet leading AI website-building options and start with one powerful prompt that works across tools.</p><ul><li>Platform-agnostic guidance</li><li>A genuinely useful starter prompt</li><li>Launch and domain essentials</li></ul><a href="#prompt">GET THE FREE STARTER KIT <Arrow/></a></article><article className="path-card done"><div className="card-top"><span>PATH 02</span><span>FOR THE BUSY</span></div><div className="path-icon">✦</div><h3>HAVE US BUILD<br/>IT — <i>FREE</i></h3><p>Tell us about your business or organization. If we select your project, we’ll design and present a website before you pay anything.</p><ul><li>No upfront design fee</li><li>See what we can create first</li><li>No obligation to continue</li></ul><a href="#apply">TELL US ABOUT YOUR PROJECT <Arrow/></a></article></div></div></section>
  <section className="kit shell"><p className="section-num">03 / THE FREESITES FREE WEBSITE STARTER KIT</p><div className="kit-head"><h2>YOUR FREE WEBSITE<br/><i>STARTER KIT.</i></h2><p>Everything you need to understand the new landscape, make a smart first move and get your website started with confidence.</p></div><div className="kit-list">{kit.map((t,i)=><div className="kit-item" key={t}><span>{String(i+1).padStart(2,"0")}</span><strong>{t}</strong><b>FREE</b></div>)}</div></section>
  <section className="prompt-wrap" id="prompt"><div className="shell prompt-grid"><div><p className="section-num light">04 / YOUR FIRST MOVE</p><h2>One powerful<br/><i>free prompt.</i></h2><p>A useful starting point for whichever leading AI system you choose. Our private production process goes much deeper—but this will get you moving.</p></div><div className="prompt-card"><div className="prompt-label"><span>FREESITES STARTER PROMPT</span><button onClick={copyPrompt}>{copied?"COPIED ✓":"COPY PROMPT ⧉"}</button></div><p>“{starterPrompt}”</p></div></div></section>
  <section className="model shell"><p className="section-num">05 / HOW IT WORKS</p><div className="model-title"><h2>Free gets you to <i>wow.</i><br/>Then, you decide.</h2><p>FreeSites separates seeing the possibility from paying to make it operational. You can stop after the free start—with no obligation.</p></div><div className="steps"><article><b>FREE</b><h3>WOW</h3><p>We design, build and present the possibility. You see the work before paying.</p></article><article><b>OPTIONAL</b><h3>WORKING</h3><p>Choose help with publishing, domains, forms, payments, booking or integrations.</p></article><article><b>ONGOING</b><h3>GROWING</h3><p>Add hosting, optimization, CRM, SmartReply, AI voice, SMS or automation.</p></article></div></section>
  <section className="final" id="apply"><div className="shell final-inner"><p className="section-num light">THE OLD RULES NO LONGER APPLY</p><h2>Why pay thousands<br/>before you see<br/><i>what’s possible?</i></h2><a href="#start">START MY WEBSITE FREE <Arrow/></a><p>No credit card. No obligation.</p></div></section>
  <footer className="shell"><div className="footer-top"><a className="wordmark" href="#top"><span>Free</span>Sites</a><p>Independent guidance and expert implementation<br/>for the new era of website building.</p></div><div className="footer-links"><span>© 2026 FreeSites</span><div><a href="/privacy">Privacy Policy</a><a href="/terms">Terms</a><a href="mailto:admin@freesites.com">Contact</a><a href="/affiliate-disclosure">Affiliate Disclosure</a><a href="/funding">Funding</a></div></div><p className="made-with">Made with <span aria-label="love">❤️</span> by <a href="https://www.freesites.com/">FreeSites</a></p><p className="legal" id="legal">Third-party AI tools have their own terms, pricing and limitations. “FREE” refers to the specific FreeSites offers described and/or free capabilities available from third-party tools, which may change. FreeSites is independent and is not necessarily affiliated with or endorsed by companies mentioned. FreeSites selectively chooses projects for its free done-for-you build offer. Additional customization, installation, integrations, hosting, maintenance and other services may cost extra. A free build creates no obligation to purchase additional services. Some links may eventually be affiliate links; any such relationship will be clearly disclosed.</p></footer>
 </main>
}
